Implement `-s`/`--squash` feature

diff --git a/git-edit b/git-edit
--- a/git-edit
+++ b/git-edit
@@ -1,7 +1,7 @@
 #!/bin/zsh
 
 # git edit – Easily edit commits via interactive rebase
-# usage: `git edit [-m | --message | -d | --drop] <commit>`
+# usage: `git-edit [-m | --message | -d | --drop | -s | --squash] <commit>`
 #
 # This Git command script allows you to edit/modify/modify
 # previous Git commits easily. It essentially is a more
@@ -16,9 +16,11 @@
 # so you can manually resolve them before continuing with the
 # merge/rebase. After completion, your previous local changes
 # will be unstashed/reapplied.
+#
 # If you want to alter the commit message as well, add the
-# `-m` switch.
-# You can also drop (delete) a commit by using `-d` instead.
+# `-m` switch. You can also delete (drop) a commit by using
+# `-d` instead, or merge (fixup/squash) it into the previous one
+# using `-s`/`--squash`.
 #
 # Use it as "git edit" by adding its parent folder to your PATH,
 # e.g. by adding this line to ~./zshrc:
@@ -44,10 +46,11 @@ echo -e "\e[1;96mgit edit – Easily edit commits via interactive rebase\e[0m"
 # ------------------------------------------- FUNCTIONS --------------------------------------------
 
 USAGE () {
-	echo -e "\e[0;96musage: git edit [-m | --message | -d | --drop] <commit>\e[0m"
+	echo -e "\e[0;96musage: git edit [-m | --message | -d | --drop | -s | --squash] <commit>\e[0m"
 	echo -e ""
 	echo -e "\e[0;96m       -m, --message     Alter commit message after editing\e[0m"
-	echo -e "\e[0;96m       -d, --drop        Just drop (delete) the commit\e[0m"
+	echo -e "\e[0;96m       -d, --drop        Just delete (drop) the commit\e[0m"
+	echo -e "\e[0;96m       -s, --squash      Merge (fixup/squash) this commit into the previous one\e[0m"
 	echo -e ""
 }
 
@@ -75,6 +78,24 @@ GIT_REBASE_DROP () {
 	GIT_SEQUENCE_EDITOR="sed -i -e 's/^pick $COMMIT_SHORT/drop $COMMIT_SHORT/'" git "${CMD[@]}" || ABORT
 }
 
+GIT_REBASE_SQUASH () {
+	CMD=(rebase --interactive "$COMMIT_SHORT~2")
+	echo -e "\n\e[0;97mgit ${CMD[*]} # -> squash\e[0;90m"
+
+	OUTPUT=$(GIT_SEQUENCE_EDITOR="sed -i -e 's/^pick $COMMIT_SHORT/squash $COMMIT_SHORT/'" git "${CMD[@]}" 2>&1 | tee /dev/stderr)
+	STATUS=$?
+	GIT_REBASE_HANDLE_ERRORS "$OUTPUT" $STATUS
+}
+
+GIT_REBASE_FIXUP () {
+	CMD=(rebase --interactive "$COMMIT_SHORT~2")
+	echo -e "\n\e[0;97mgit ${CMD[*]} # -> fixup\e[0;90m"
+
+	OUTPUT=$(GIT_SEQUENCE_EDITOR="sed -i -e 's/^pick $COMMIT_SHORT/fixup $COMMIT_SHORT/'" git "${CMD[@]}" 2>&1 | tee /dev/stderr)
+	STATUS=$?
+	GIT_REBASE_HANDLE_ERRORS "$OUTPUT" $STATUS
+}
+
 GIT_REBASE_BEGIN_EDIT () {
 	# Determine if commit has a parent or is the first commit
 	if git show -s --pretty=%P "$COMMIT_SHORT" | grep -q .; then
@@ -94,7 +115,7 @@ GIT_ADD_ALL () {
 }
 
 GIT_COMMIT_AMEND () {
-	if [[ "$ACTION" == "edit+message" ]]; then
+	if [ ${#OPT_MESSAGE} -gt 0 ]; then
 		CMD="git commit --all --amend"
 	else
 		CMD="git commit --all --amend --no-edit"
@@ -104,10 +125,20 @@ GIT_COMMIT_AMEND () {
 }
 
 GIT_REBASE_CONTINUE () {
-	CMD="git rebase ${1:---continue}"
+	# First arg is the rebase sub-command, defaulting to "--continue"
+	local SUBCMD="${1:---continue}"
+
+	CMD="git rebase $SUBCMD"
 	echo -e "\n\e[0;97m$CMD\e[0;90m"
 	OUTPUT=$(eval "GIT_EDITOR=true $CMD" 2>&1 | tee /dev/stderr)
 	STATUS=$?
+
+	GIT_REBASE_HANDLE_ERRORS "$OUTPUT" $STATUS
+}
+
+GIT_REBASE_HANDLE_ERRORS () {
+	local OUTPUT="$1"
+	local STATUS=$2
 
 	if [[ $STATUS -ne 0 ]]; then
 		if [[ "$OUTPUT" == *"CONFLICT (content)"* ]]; then
@@ -163,7 +194,7 @@ ABORT () {
 # -K allows us to set default values without zparseopts overwriting them
 # (the first dash is automatically handled, so long options are -opt, not --opt)
 zmodload zsh/zutil
-if ! zparseopts -D -E -F -K -- {m,-message}=OPT_MESSAGE {d,-drop}=OPT_DROP {h,-help}=OPT_HELP; then
+if ! zparseopts -D -E -F -K -- {m,-message}=OPT_MESSAGE {d,-drop}=OPT_DROP {s,-squash}=OPT_SQUASH {h,-help}=OPT_HELP; then
 	USAGE
 	echo -e "\e[0;91mUnknown option: $1\e[0m"
 	exit 1
@@ -175,16 +206,23 @@ if [[ ${#OPT_HELP} -gt 0 || $1 == "help" ]]; then
 	exit 0
 fi
 
-# -m/--message | -d/--drop
+# -m/--message + -d/--drop
 if [ ${#OPT_MESSAGE} -gt 0 -a ${#OPT_DROP} -gt 0 ]; then
 	USAGE
 	echo -e "\e[0;91mOptions -m/--message and -d/--drop cannot be combined\e[0m"
 	exit 1
 fi
+# -d/--drop + -s/--squash
+if [ ${#OPT_DROP} -gt 0 -a ${#OPT_SQUASH} -gt 0 ]; then
+	USAGE
+	echo -e "\e[0;91mOptions -d/--drop and -s/--squash cannot be combined\e[0m"
+	exit 1
+fi
+# -d/--drop | -s/--squash
 if [ ${#OPT_DROP} -gt 0 ]; then
 	ACTION="drop"
-elif [ ${#OPT_MESSAGE} -gt 0 ]; then
-	ACTION="edit+message"
+elif [ ${#OPT_SQUASH} -gt 0 ]; then
+	ACTION="squash"
 else
 	ACTION="edit"
 fi
@@ -219,6 +257,14 @@ if [[ "$ACTION" == "drop" ]]; then
 	echo -e "\n\e[1;96mDropping commit \e[0;96m$COMMIT_SHORT\e[0m"
 
 	GIT_REBASE_DROP
+elif [[ "$ACTION" == "squash" ]]; then
+	echo -e "\n\e[1;96mMerging commit \e[0;96m$COMMIT_SHORT\e[1;96m into previous commit\e[0m"
+
+	if [ ${#OPT_MESSAGE} -gt 0 ]; then
+		GIT_REBASE_SQUASH
+	else
+		GIT_REBASE_FIXUP
+	fi
 else
 	GIT_REBASE_BEGIN_EDIT
 	 
